### ISSUE TITLE
Paper Comments

### ISSUE THREAD

**Issue by davidogara** [davidogara/hetGPy#14]
From @Edenhofer, available at https://github.com/openjournals/joss-reviews/issues/7518#issuecomment-2515170196:

The paper is well written and contains all the essential information that a reader might want to know about the software. I have no major points of feedback regarding the scientific content of the paper. However, I would suggest to run a grammar checker on the text. There are several duplications of partial sentences in the paper. In the following are a few minor comments about a few specific sections.

- l21 heteroskedasticity is defined more generally as non equal variance noise (not necessarily input dependent)
- l22 “these both of these”; language
- l21ff IMO the sentence is a bit overloaded and hard to read. Please rephrase.
- l23 here and in the following, please be more specific with what you mean with “replicas”/“replication”. I think you mean multiple observations at the same location. I would suggest spelling this out instead of using the term “replication”.
- l46 the default behavior of a library is not too relevant. Rather say whether these libraries can do that. It’s been a while since I’ve - used them but AFAIK some of these libraries support learning the mean and variance.
- l47 “as in common in”; language
- l49 Could the authors briefly elaborate on why hetGPy is more computationally efficient.
- l55 “several orders of magnitude” the table shows a significant improvement but not over “several orders of magnitude”
- l66 the second citation should probably not be in brackets
- l72 “see that the for the SK case”; language

**Comment by davidogara** [comment]
Thanks for pointing these out and for the close read @Edenhofer -- I opened this issue so we have a place to discuss (and I hope to address these soon)

**Comment by DanWaxman** [comment]
Also as part of https://github.com/openjournals/joss-reviews/issues/7518, I will add my paper comments here.

- There are unused affiliations -- looking briefly, it looks like these should be attached to Ross A Hammond.
- (L17) The citation here should be at the end of the sentence.
- (L21-L25) I also think this sentence should be broken up into several sentences and rephrased.
- (L33) This is very nitpicky but PyTorch is typically stylized as "PyTorch" or `torch`, not `pytorch`.
- (L39) `rpy2` should be cited (see e.g., https://joss.theoj.org/papers/10.21105/joss.00862.pdf)
- (Figure 1b) Please add units to the run times (i.e., "hetGPy (0.08s)", etc.)
- (L68) "Homoscedastic" is written here, but spelt with a "k" everywhere else. Either one is fine, but should be consistent.
- (L91) This citation does not render properly.
- (L104) "R" should be capitalized.
- (L172) The citation for Surjanovic & Bingham should have a year and URL, since it's a website. They suggest 2013 as the year on the website (https://www.sfu.ca/~ssurjano/about.html).

**Comment by DanWaxman** [comment]
Also, as a very small additional comment, it is mentioned that "[hetGPy] is well-posed to engage with the wider Python community for future extension such as arbitrary kernel functions with auto-differentiation methods facilitated by PyTorch." It probably makes sense here to mention `jax` rather than `numpy`, since `jax.numpy` implements (with caveats) the majority of the `numpy` API directly.

**Comment by davidogara** [comment]
@Edenhofer @DanWaxman  I've gotten a address your comments on the paper. I've repasted the more substantive ones (many of them I just addressed by fixing typos). Since many of your comments overlapped I decided to address them at the same time, but I'd be happy to break these into separate comments

For @Edenhofer:
- l21ff IMO the sentence is a bit overloaded and hard to read. Please rephrase.
   - Thanks, I re-worked this and the following sentences to hopefully be more clear, but please let me know if it is not
- l23 here and in the following, please be more specific with what you mean with “replicas”/“replication”. I think you mean multiple observations at the same location. I would suggest spelling this out instead of using the term “replication”.
   - Thanks for mentioning this: I re-worked this sentence to more specifically spell out what I mean by replicates (and you are correct, that it is multiple observations at the same input location) 
- l46 the default behavior of a library is not too relevant. Rather say whether these libraries can do that. It’s been a while since I’ve - used them but AFAIK some of these libraries support learning the mean and variance.
  - Thanks, I re-worded to mention
- l49 Could the authors briefly elaborate on why hetGPy is more computationally efficient.
  - Yes, I made it more explicit in the text (that hetGPy solves a problem of size n=1000 rather than N=~5000 in these examples), which combined with the explanation around line 20, should make things more clear



And for @DanWaxman:

- (L21-L25) I also think this sentence should be broken up into several sentences and rephrased. 
   - Thanks, I re-worked this section by breaking it up into several sentences which should hopefully help the explanation

Thank you both again for your feedback on the paper. Please let me know if you have any follow-up and I'd be happy to address it.

**Comment by Edenhofer** [comment]
Thanks for the update. Could you please resolve the following and share a link to the updated PDF ? https://github.com/openjournals/joss-reviews/issues/7518#issuecomment-2548222082

**Comment by davidogara** [comment]
Thank you! You should be able to download the paper proof from this link:
https://github.com/openjournals/joss-reviews/issues/7518#issuecomment-2548889664

**Comment by DanWaxman** [comment]
Thanks, these changes look good! As a remaining typo, on (L43) there should be a space after "rpy2".

**Comment by davidogara** [comment]
Thanks @DanWaxman! I addressed that last typo.

**Comment by Edenhofer** [comment]
Thanks for your work on refining the paper. I am happy with the changes and have no further comments :)

**Comment by davidogara** [comment]
Thank you both! In that case, I will close the issue.
